### ISSUE TITLE
Dead link to http://www.r-inla-download.org/

### ISSUE THREAD

**Issue by RPanczak** [hrue/r-inla#44]
http://www.r-inla-download.org/ in README points to 403 forbidden

**Comment by finnlindgren** [comment]
Yes, it should probably be https://inla.r-inla-download.org/ instead.

**Comment by RPanczak** [comment]
Indeed, thanks! 💪

**Comment by finnlindgren** [comment]
But https://www.r-inla.org/download-install is a better starting point. Also note that there is no R4.2 build available yet; you'll need e.g. R4.1.3 until that's sorted out, which may take a while.

**Comment by RPanczak** [comment]
Roger that. Will most likely need 4.1 this time.

**Comment by hrue** [comment]
thanks. its fixed. should be inla.r-inla-download.org


-- 
Håvard Rue
Professor of Statistics
Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue
Zoom.office: Meeting ID 510 522 9264

-----Original Message-----
From: Radoslaw Panczak ***@***.***>
Reply-To: hrue/r-inla
***@***.***>
To: hrue/r-inla ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BULK] [hrue/r-inla] Dead link to
http://www.r-inla-download.org/ (Issue #44)
Date: Thu, 28 Apr 2022 07:59:55 -0700

http://www.r-inla-download.org/ in README points to 403 forbidden
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>
