### ISSUE TITLE
Error in inla.call.builtin() : INLA installation error; no such file

### ISSUE THREAD

**Issue by Ruben7c** [hrue/r-inla#45]
Hi, I'm having the same problem and when I try installing the testing version I got this error:

* installing *binary* package 'INLA' ...
cp: unknown option -- )
Try '/usr/bin/cp --help' for more information.
ERROR: installing binary package failed
* removing 'H:/R/R-4.1.2/library/INLA'
* restoring previous 'H:/R/R-4.1.2/library/INLA'
Warning in install.packages :
  installation of package ‘INLA’ had non-zero exit status

Could you help with this?

Thanks

**Comment by hrue** [comment]
since there is a 'source' package that is newer (and we now build for R-
4.2) you need to add argument

type="binary"

to install.packages(), to get the binary package for R-4.1



install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing
"), type="binary", dep=TRUE)



install_github() does not work

**Comment by Ruben7c** [comment]
Thanks for the quick response, now it's working.

Cheers!
