### ISSUE TITLE
Please remove Suggests: dependencies on rgdal and rgeos

### ISSUE THREAD

**Issue by rsbivand** [hrue/r-inla#70]
Please see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html. **sp** will use **sf** instead of **rgdal** from June 2023 (evolution status shift from 0 to 2); we expect to retire **rgdal**, **rgeos** and **maptools** by October 2023.

**Comment by finnlindgren** [comment]
The relevant parts of INLA will be converted to call the new methods in inlabru and fmesher to avoid these dependencies. The inlabru conversion is nearly finished (I'm removing the rgdal dependency there right now. :) )
Adding cross-reference to keep track of both package statuses: https://github.com/inlabru-org/inlabru/issues/178

**Comment by WorksAtAUni** [comment]
this would be nice....

**Comment by finnlindgren** [comment]
The direct `rgdal` and `rgeos` dependencies in INLA have been removed since 2023.01.31. This has also been fixed in the `inlabru` development version, that will soon go onto CRAN. This bug report is being kept open until all the transition elements have been completed, as well as for when the case-studies and related document for the r-inla website have transitioned away from using `rgdal`/`rgeos`/`maptools`.
